
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET

#define PERMISSIVE_HOLD
#define TRI_LAYER_LOWER_LAYER 1
#define TRI_LAYER_UPPER_LAYER 2
#define TRI_LAYER_ADJUST_LAYER 4

#define WS2812_DI_PIN GP11
#define WS2812_RGB
#define RGB_MATRIX_LED_COUNT 60
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 30
#define RGB_MATRIX_DEFAULT_HUE 0
#define RGB_MATRIX_DEFAULT_SAT 0
#define RGB_MATRIX_DEFAULT_VAL 80

#define ENCODER_A_PINS { GP14 }
#define ENCODER_B_PINS { GP15}
#define DIP_SWITCH_PINS { GP16 }

#define OLED_DRIVER SSD1306
#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP13
#define I2C1_SCL_PIN GP9
