#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define DEBUG_MATRIX_SCAN_RATE

#define ENCODER_A_PINS { GP20, GP8}
#define ENCODER_B_PINS { GP23, GP7}
#define ENCODER_RESOLUTION 4
#define DIP_SWITCH_PINS { GP21, GP9 }

#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP15
#define I2C1_SCL_PIN GP14

#define AUTO_SHIFT_TIMEOUT 150
#define RETRO_SHIFT 200
#define AUTO_SHIFT_MODIFIERS

#define ENC_1_MODE_COUNT 2
#define ENC_2_MODE_COUNT 2


#define MOUSE_SPEED_STEP 1
#define MOUSEKEY_TIME_TO_MAX 45


