#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define DEBUG_MATRIX_SCAN_RATE

#define ENCODER_A_PINS { GP20, GP8}
#define ENCODER_B_PINS { GP23, GP7}
#define ENCODER_RESOLUTION 4
#define DIP_SWITCH_PINS { GP21, GP9 }

#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP15
#define I2C1_SCL_PIN GP14

// #define AUTO_SHIFT_TIMEOUT 150
// #define RETRO_SHIFT 200
// #define AUTO_SHIFT_MODIFIERS
