CONSOLE_ENABLE = yes
ENCODER_ENABLE = yes
DIP_SWITCH_ENABLE = yes

TAP_DANCE_ENABLE = yes
CAPS_WORD_ENABLE = yes
AUTO_SHIFT_ENABLE = yes

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = azoteq_iqs5xx

