CONSOLE_ENABLE = yes
ENCODER_ENABLE = yes
DIP_SWITCH_ENABLE = yes

TAP_DANCE_ENABLE = yes
CAPS_WORD_ENABLE = yes

OLED_ENABLE = yes
OLED_DRIVER = ssd1306
OLED_TRANSPORT = i2c

MOUSEKEY_ENABLE = yes
COMBO_ENABLE = yes
UNICODE_ENABLE = yes
